apps/abouts/urls.py
from django.urls import path

from apps.abouts import views
app_name = 'about'
urlpatterns = [
    path('', views.about, name='about-page'),
]

apps/carts/urls.py
from django.urls import path

from apps.carts import views
app_name = 'carts'

urlpatterns = [
    path('cart_page/', views.cart_page, name='cart-page'),
    path('create_cart/<int:product_id>/', views.create_cart, name='create-cart' ),
    path('delete_cart/<int:product_id>/', views.delete_cart, name='delete-cart'),
    path('set/<int:cart_id>/', views.set_cart_quantity, name='set-cart-quantity'),
]

apps/contact/urls.py
from django.urls import path

from apps.contact.views import contact_us

app_name = 'contacts'
urlpatterns = [
    path('', contact_us, name='contact-us')
]

apps/coupons/urls.py
from django.urls import path
from apps.coupons.views import check_coupon

app_name = 'coupn'
urlpatterns = [
    path('check/', check_coupon, name='check-coupon')
]

apps/wishlists/urls.py
from django.urls import path

from apps.wishlists import views

app_name = "wishlists"
urlpatterns = [
    path('wishlist_create/', views.wishlist_create, name='wishlist-create'),
    path('', views.wishlist_page, name='wishlist-page'),
    path('delete_wishlist/<int:product_id>', views.wishlist_delete, name='wishlist-delete'),
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

from apps.main.views import home

from apps.categories.views import category, set_category
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # ========== set language =========
    path('searchs/', include('apps.general.urls', namespace='searchs')),

    #================ Debug toolbars =============
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += i18n_patterns(

    # ========== about urls ===========
    path('about/', include('apps.abouts.urls', namespace='about')),

    #=========== wishlist =================
    path('wishlists/', include('apps.wishlists.urls', namespace='wishlist')),

    #=========== comment ================
    path('comments/', include('apps.comments.urls', namespace='comments')),

    #=========== admin ===========
    path('admin/', admin.site.urls),

    #============= home ============
    path('', home, name='home-page'),

    #=============contact=============
    path('contact/', include('apps.contact.urls', namespace='contacts')),

   #============ checkout ==============
    path('checkout/', include('apps.orders.urls')),

   #=========== products ====================
    path('products/', include('apps.products.urls', namespace='products')),

    #============== category ============
    path('category/', category, name='category-page'),
    path('set_category/<int:cat_id>/', set_category, name='set-category'),

    #=============== cart ===========================
    path('cart/', include('apps.carts.urls', namespace='carts')),

    #================== authentications ======================
    path('authentications/', include('apps.authentication.urls', namespace='authentications')),

    #================== coupon ===========================
    path('coup/', include('apps.coupons.urls', namespace='coupn')),

    #====================== Media =========================
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

)

apps/abouts/models.py
from django.db import models

class About(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    image = models.ImageField(upload_to='abouts/images/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.title

apps/carts/models.py
from django.conf import settings
from django.db import models



class ProductCard(models.Model):

    product = models.ForeignKey(to='products.Product', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    class Meta:
        unique_together = (('user', 'product'),)

apps/contact/models.py
from django.db import models
class Contact(models.Model):
    first_name = models.CharField(max_length=200)
    email = models.EmailField()
    user_subject = models.CharField(max_length=500)
    user_message = models.CharField(max_length=500)


    def __str__(self):
        return self.first_name

apps/wishlists/models.py
from django.conf import settings
from django.db import models



class Wishlist(models.Model):
    class Meta:
        unique_together = (('user', 'product'),)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(to='products.Product', on_delete=models.CASCADE)

apps/contact/forms.py
from django.forms import ModelForm

from apps.contact.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

apps/wishlists/forms.py
from django import forms

class WishlistForm(forms.Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput())

apps/abouts/views.py
from django.shortcuts import render

from apps.abouts.models import About


def about(request):
    """
    this about function
    there context use for html, it got all obj
    """
    context = {
               'abouts': About.objects.all(),
    }
    return render(request=request, template_name='about.html', context=context)

apps/carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from apps.carts.models import ProductCard
from django.db.models import F, Sum
from apps.coupons.models import UsedCoupon, Coupon
from apps.general.models import General


@login_required
def cart_page(request):
    try:
        shipping_percent = General.objects.first().shipping_percent
    except AttributeError:
        shipping_percent = 0

    user = request.user
    code = request.session.get('coupon_data', {}).get('code')
    if code is not None and UsedCoupon.objects.filter(coupon__code=code, user_id=user.pk).exists():
        del request.session['coupon_data']
    queryset = ProductCard.objects.annotate(total_price=F('quantity') * F('product__price')).filter(user=request.user)
    cart_total_price = queryset.aggregate(s=Sum('total_price',default=0))['s']

    context = {
        'cart_user': queryset.select_related('product'),
        'cart_total_price': cart_total_price,
        'shipping_percent': shipping_percent,
    }
    context['total_price'] = context["cart_total_price"] * shipping_percent / 100 + context["cart_total_price"] - request.session.get('coupon_data', {}).get('discount_percent', 0) * context["cart_total_price"]/100
    return render(request=request, template_name='cart.html', context=context)


@login_required
def create_cart(request, product_id):
    obj, create = ProductCard.objects.get_or_create(user_id=request.user.id, product_id=product_id)
    quantity = request.POST.get('cart_quantity', 1)

    print(quantity)

    if obj.quantity != quantity:
        obj.quantity = quantity
        obj.save()

    if not create:
        obj.delete()

    return redirect(request.META['HTTP_REFERER'])


def delete_cart(request, product_id):
    """
    This view deletes a Product Cart from the database.
    """
    if request.user.is_authenticated:
        ProductCard.objects.filter(user_id=request.user.id, product_id=product_id).delete()
    return redirect(request.META['HTTP_REFERER'])




def set_cart_quantity(request, cart_id):
    if request.method != 'POST':
        return redirect('home-page')

    cart_obj = get_object_or_404(ProductCard, pk=cart_id)
    quantity = request.POST.get('item_quantity', cart_obj.quantity)
    if quantity.isdigit() and int(quantity) <= 0:
        cart_obj.delete()
    else:
        cart_obj.quantity = quantity
        cart_obj.save()
    return redirect(request.META['HTTP_REFERER'])

apps/contact/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from apps.contact.forms import ContactForm
from apps.contact.models import Contact


def contact_us(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'Success contact made so easy')
            return render(request=request, template_name='contact.html')
        else:
            messages.error(request, contact_form.errors)
    return render(request=request, template_name='contact.html')

apps/wishlists/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from apps.products.models import Product
from apps.wishlists.forms import WishlistForm
from apps.wishlists.models import Wishlist


def wishlist_page(request):
    if request.user.is_authenticated:
        wishlists_user = Wishlist.objects.filter(user=request.user).select_related('product')

    else:
        wishlists_user = None
    context = {
        # 'wishlists': Wishlist.objects.select_related('user', 'product'),
        'wishlists': wishlists_user,
    }
    return render(request=request, template_name="wishlist.html", context=context)

@login_required
def wishlist_create(request):
    if request.method == 'POST':
        form = WishlistForm(request.POST)
        if form.is_valid():
            product_id = form.cleaned_data['product_id']
            product = get_object_or_404(Product, id=product_id)

            wish, created = Wishlist.objects.get_or_create(user=request.user, product=product)

            if not created:
                wish.delete()

            return redirect(request.META.get('HTTP_REFERER', 'products:product_list'))


def wishlist_delete(request, product_id):
    """
    This view deletes a wishlist from the database.
    """

    if request.user.is_authenticated:
        Wishlist.objects.filter(user_id=request.user.id, product_id=product_id).delete()
    return redirect(request.META['HTTP_REFERER'])

templates/about.html
{% extends 'bases/basic.html' %}
{% block content %}
    {% load static %}
    {% load i18n %}
    
    <!-- Breadcrumb Start -->
   {% include 'includes/breadcrumb.html' with page='About' %}
    <!-- Breadcrumb End -->

    <!-- About Start -->
    <div class="container-fluid about py-5">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-lg-5">
                    <div class="h-100"
                         style="border: 50px solid; border-color: transparent #13357B transparent #13357B;">
                        {% for about1 in abouts %}
                            <img src="{{ about1.image.url }}" class="img-fluid w-100 h-100" alt="">
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-7"
                     style="background: linear-gradient(rgba(255, 255, 255, .8), rgba(255, 255, 255, .8)), {% static 'about ing/about-img-1.png' %};">
                    <h5 class="section-about-title pe-3">{% translate 'About Us' %}s</h5>
                    {% for about in abouts %}
                        <h1 class="mb-4"><span class="text-primary"><h2>{{ about.title|truncatechars:50 }}</h2></span></h1>
                        <h2>{{ about.description|truncatechars:50 }}</h2>
                    {% endfor %}
                    <div class="row gy-2 gx-4 mb-4">
                        {#                        {% for foo in social_media %}#}
                        <div class="col-sm-6">
                            <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>{{ abouts.title }}
                            </p>
                        </div>
                        {#                        {% endfor %}#}
                    </div>

                    <a class="btn btn-primary rounded-pill py-3 px-5 mt-2" href="">Read More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

{% endblock content %}

templates/cart.html
{% extends 'bases/basic.html' %}
{% load static %}
{% load coupon_tags %}
{% load i18n %}
{% block content %}

<!-- Breadcrumb Start -->
{% include 'includes/breadcrumb.html' with page='Shopping cart' %}
<!-- Breadcrumb End -->

<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                <tr>
                    <th>{% translate 'Products' %}</th>
                    <th>{% translate 'Price' %}</th>
                    <th>{% translate 'Quantity' %}</th>
                    <th>{% translate 'Total' %}</th>
                    <th>{% translate 'Remove' %}</th>
                </tr>
                </thead>
                <tbody class="align-middle">
                {% for cart in cart_user %}
                <tr>
                    <td class="align-middle"><img src="{{ cart.product.main_image.url }}" alt=""
                                                  style="width: 50px;"> Product Name
                    </td>
                    <td class="align-middle">${{ cart.product.price }}</td>
                    <td class="align-middle">
                        <form action="{% url 'carts:set-cart-quantity' cart.pk %}" method="post">
                            {% csrf_token %}
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input name="item_quantity" type="text"
                                       class="form-control form-control-sm bg-secondary border-0 text-center"
                                       value="{{ cart.quantity }}">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </td>

                    <td class="align-middle">${{ cart.total_price }}</td>
                    <td class="align-middle">
                        <button class="btn btn-sm btn-danger">
                            <a class="btn btn-sm btn-danger"
                               href="{% url 'carts:delete-cart' product_id=cart.product.id %}">
                                <i class="fa fa-times"></i>
                            </a>

                        </button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
            <form class="mb-30" action="{% url 'coupn:check-coupon' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" required class="form-control border-0 p-4" placeholder="Coupon Code"
                           name="coupon_code" value="{{ request.session.coupon_data.code }}">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span
                    class="bg-secondary pr-3">Cart Summary</span>
            </h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>{{ cart_total_price }} {% if request.session.currency %} {{ request.session.currency }} {% else %}
                            SUM {% endif %}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">{{ shipping_percent}} %</h6>
                    </div>
                        {% if request.session.coupon_data %}
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Coupon</h6>
                                <h6 class="font-weight-medium">{{ request.session.coupon_data.discount_percent }} %</h6>
                            </div>
                        {% endif %}
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5> {{ total_price }} {{currency}} </h5>
                    </div>
                    <a href="{% url 'checkout-page' %}">
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To
                            Checkout
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Cart End -->

{% endblock content %}

templates/checkout.html
{% extends 'bases/basic.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    {% include 'includes/breadcrumb.html' with page='Checkout' %}
    <!-- Breadcrumb End -->


    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Billing Address</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="row">

                        <div class="col-md-12">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="shipto">
                                <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">Ship to different address</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse mb-5" id="shipping-address">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Shipping Address</span></h5>
                    <div class="bg-light p-30">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label>First Name</label>
                                <input class="form-control" type="text" placeholder="John">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Last Name</label>
                                <input class="form-control" type="text" placeholder="Doe">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>E-mail</label>
                                <input class="form-control" type="text" placeholder="example@email.com">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Mobile No</label>
                                <input class="form-control" type="text" placeholder="+123 456 789">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Address Line 1</label>
                                <input class="form-control" type="text" placeholder="123 Street">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Address Line 2</label>
                                <input class="form-control" type="text" placeholder="123 Street">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Country</label>
                                <select class="custom-select">
                                    <option selected>United States</option>
                                    <option>Afghanistan</option>
                                    <option>Albania</option>
                                    <option>Algeria</option>
                                </select>
                            </div>
                            <div class="col-md-6 form-group">
                                <label>City</label>
                                <input class="form-control" type="text" placeholder="New York">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>State</label>
                                <input class="form-control" type="text" placeholder="New York">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>ZIP Code</label>
                                <input class="form-control" type="text" placeholder="123">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom">
                        <h6 class="mb-3">Products</h6>
                            {% for cart in carts %}
                                 <div class="d-flex justify-content-between">
                                     <p>{{ cart.product|truncatewords:3 }}</p>
                                     <p>{{ cart.quantity }} x {{ cart.product.price }} {{ currency }}</p>

                                 </div>
                            {% endfor %}


                    </div>
                    <div class="border-bottom pt-3 pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>{{ total_cart }} {{ currency }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">{{ shipping_percent }} %</h6>
                        </div>
                        {% if request.session.coupon_data %}
                         <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Coupon</h6>
                            <h6 class="font-weight-medium">{{ request.session.coupon_data.discount_percent }} %</h6>
                        </div>
                        {% endif %}
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>{{ total_sum }} {{currency }}</h5>
                        </div>
                    </div>
                </div>
                <div class="mb-5">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5>
                    <div class="bg-light p-30">
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="paypal">
                                <label class="custom-control-label" for="paypal">Paypal</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                <label class="custom-control-label" for="directcheck">Direct Check</label>
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold py-3">Place Order</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->


{% endblock content %}

templates/test.html
<p>
    <form method="post">
        {% csrf_token %}
        {{ forms }}
        <button>create</button>
    </form>

</p>

<p>
    {{ forms.errors }}
</p>

templates/wishlist.html
{% extends 'bases/basic.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    {% include 'includes/breadcrumb.html' with page='Shopping cart' %}
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for wishlist in wishlists %}
                    	<tr>
                        {% if wishlist.product.main_image %}
                            <td class="align-middle"><img src="{{ wishlist.product.main_image.url }}" alt="" style="width: 50px;"></td>
                            <td class="align-middle">alt="" style="width: 50px;">{{ wishlist.product.title }}</td>

                        {% else %}
                            <td class="align-middle"><img src="{% static 'img/istockphoto-884072610-612x612.jpg' %}" alt="" style="width: 50px;">{{ wishlist.product.title }}</td>
                        {% endif %}    
                            <td class="align-middle">{{ wishlist.product.price }}</td>
                            <td class="align-middle">
                                <a class="btn btn-sm btn-danger" href="{% url 'wishlists:wishlist-delete' product_id=wishlist.product.id %}">
                                    <i class="fa fa-times"></i>   
                                
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock content %}